import AppKit

/// Watches the general pasteboard. There is no change notification on macOS, so polling
/// `changeCount` is the only option — it is a cheap integer read.
@MainActor
final class ClipboardMonitor {

    static let shared = ClipboardMonitor()

    private let pasteboard: NSPasteboard
    private var lastChangeCount: Int
    private var timer: Timer?

    /// Types we bother to keep. Apps routinely advertise a dozen private flavours; storing them
    /// all would balloon memory for no benefit.
    private static let capturedTypes: [NSPasteboard.PasteboardType] = [
        .string, .rtf, .rtfd, .html, .png, .tiff, .fileURL, .URL, .pdf
    ]

    /// Set by apps that handle secrets (1Password, Bitwarden, KeePassXC, …). Never record these.
    private static let concealed = NSPasteboard.PasteboardType("org.nspasteboard.ConcealedType")
    private static let transient = NSPasteboard.PasteboardType("org.nspasteboard.TransientType")
    private static let autoGenerated = NSPasteboard.PasteboardType("org.nspasteboard.AutoGeneratedType")

    /// Tests pass a private `NSPasteboard(name:)` so they can exercise `capture()` against
    /// real pasteboard data without disturbing the user's clipboard.
    init(pasteboard: NSPasteboard = .general) {
        self.pasteboard = pasteboard
        self.lastChangeCount = pasteboard.changeCount
    }

    func start() {
        stop()
        let timer = Timer(timeInterval: 0.3, repeats: true) { [weak self] _ in
            MainActor.assumeIsolated { self?.poll() }
        }
        // .common so polling survives menu tracking and window resizes.
        RunLoop.main.add(timer, forMode: .common)
        self.timer = timer
    }

    func stop() {
        timer?.invalidate()
        timer = nil
    }

    /// Call right after we write to the pasteboard ourselves, so our own paste isn't re-captured.
    func suppressCurrentChange() {
        lastChangeCount = pasteboard.changeCount
    }

    private func poll() {
        let current = pasteboard.changeCount
        guard current != lastChangeCount else { return }
        lastChangeCount = current
        guard let item = capture() else { return }
        ClipboardStore.shared.add(item)
    }

    // Internal rather than private so the test suite can drive it directly.
    func capture() -> ClipboardItem? {
        let types = Set(pasteboard.types ?? [])
        guard !types.isEmpty else { return nil }

        // Honour the nspasteboard.org opt-out markers.
        if types.contains(Self.concealed) || types.contains(Self.transient)
            || types.contains(Self.autoGenerated) {
            return nil
        }

        var representations: [NSPasteboard.PasteboardType: Data] = [:]
        for type in Self.capturedTypes where types.contains(type) {
            if let data = pasteboard.data(forType: type), !data.isEmpty {
                representations[type] = data
            }
        }
        guard !representations.isEmpty else { return nil }

        // One bitmap flavour, not two of the same pixels — this is where the memory goes.
        representations = Bitmap.collapsingDuplicates(representations)

        let source = NSWorkspace.shared.frontmostApplication
        let sourceName = source?.localizedName
        let sourceIcon = source?.icon?.scaledToFit(boundingBox: NSSize(width: 16, height: 16))

        // Files take priority: a Finder copy also carries a string flavour we don't want to win.
        if let urls = pasteboard.readObjects(forClasses: [NSURL.self],
                                             options: [.urlReadingFileURLsOnly: true]) as? [URL],
           !urls.isEmpty {
            return ClipboardItem(kind: .files,
                                 plainText: urls.map(\.path).joined(separator: "\n"),
                                 representations: representations,
                                 image: nil,
                                 fileURLs: urls,
                                 sourceAppName: sourceName,
                                 sourceAppIcon: sourceIcon)
        }

        // Decode any bitmap flavour up front. Even a plain rich-text copy can carry one, and
        // having it lets every entry show a real preview rather than a generic glyph.
        let bitmap = (representations[.png] ?? representations[.tiff]).flatMap(NSImage.init(data:))
        let string = pasteboard.string(forType: .string)
        let trimmed = string?.trimmingCharacters(in: .whitespacesAndNewlines) ?? ""

        // "Copy Image" in a browser puts the image *and* its URL on the pasteboard. Filing that
        // as text is technically true and practically useless — you copied a picture, so show
        // the picture. Only real prose outranks a bitmap.
        if let bitmap, trimmed.isEmpty || isBareURL(trimmed) {
            return ClipboardItem(kind: .image,
                                 plainText: trimmed,
                                 representations: representations,
                                 image: bitmap,
                                 fileURLs: [],
                                 sourceAppName: sourceName,
                                 sourceAppIcon: sourceIcon)
        }

        if !trimmed.isEmpty, let string {
            return ClipboardItem(kind: .text,
                                 plainText: string,
                                 representations: representations,
                                 image: bitmap,
                                 fileURLs: [],
                                 sourceAppName: sourceName,
                                 sourceAppIcon: sourceIcon)
        }

        if let bitmap {
            return ClipboardItem(kind: .image,
                                 plainText: "",
                                 representations: representations,
                                 image: bitmap,
                                 fileURLs: [],
                                 sourceAppName: sourceName,
                                 sourceAppIcon: sourceIcon)
        }

        return nil
    }

    func isBareURL(_ string: String) -> Bool {
        guard !string.contains(where: \.isNewline), string.count < 2048 else { return false }
        guard let url = URL(string: string), url.scheme != nil else { return false }
        return !string.contains(" ")
    }
}
